public class AllOperations {
    
    /*integer a=3 ; Integer b=2;
    public void Add(){
        
        Integer Sum = a+b;
        System.debug(Sum);
        
    }

    public void Sub(){
        
        Integer Sub = a-b;
        System.debug(Sub);
        
    }
    
    public void Mul(){
        
        Integer Mul = a*b;
        System.debug(Mul);
        
    }
    
    public void Div(){
        
        Integer Div = a/b;
        System.debug(Div);
        
    }*/

    //static 
    public static void Add(Integer a , Integer b){
        
       // Integer a =9; Integer b = 8;
        Integer Sum = a+b;
        System.debug(Sum);
        
    }

    public static void Sub(Integer k , Integer l){
       // Integer k =9; Integer l= 8;
        Integer Sub = k-l;
        System.debug(Sub);
        
    }
    
    public static void Mul(Integer a , Integer b){
       // Integer a =9; Integer b = 8;
        
        Integer Mul = a*b;
        System.debug(Mul);
        
    }
    
    public static void Div(Integer a , Integer b){
        //Integer a =9; Integer b = 8;
        Integer Div = a/b;
        System.debug(Div);
        
    }


}